### ISSUE TITLE
Disallow publishing packages with version 0.0.0

### ISSUE THREAD

**Issue by mcmire** [MetaMask/action-npm-publish#57]
Sometimes when adding a new package to a monorepo, the version will be set to 0.0.0 and then this "dummy" version will be accidentally published. In that case, we don't want to publish the version.

This case was already handled on the `action-publish-release` side [here](https://github.com/MetaMask/action-publish-release/pull/89). In a repo that uses that action in addition to this one (which is the case for all MetaMask repos), 0.0.0 should never be published, since that action is run before this one. However, this problem is still worth solving in case people are using this action separate from `action-publish-release`.

**Comment by Gudahtt** [comment]
I think this is still a problem for monorepos, even with the validation in `action-publish-release`. We've noticed `0.0.0` versions published in the core repo lately for example

**Comment by desi** [comment]
Blocked by CI issue in the repository.
